"""empty message

Revision ID: 1646ea9b5911
Revises: ee2c509af27e
Create Date: 2021-06-18 16:09:11.016458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1646ea9b5911'
down_revision = 'ee2c509af27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'lala')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('lala', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
